[package]
name = "vdom"
version = "0.1.0"
authors = ["kazatsuyu <shirayama.kazatsuyu@gmail.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
serde_derive = "1.0.118"
serde = "1.0.118"
