[package]
name = "sulafat-macros"
version = "0.1.0"
authors = ["kazatsuyu <shirayama.kazatsuyu@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]

[dependencies.sulafat-macros-impl]
path = "../macros-impl"
